///$tab 010_Transform_50+_60+_70+
// Populate 50+, 60+, 70+ target groups base on accumulation of age groups 
// QVD_Vaccination:
// LOAD * Inline [Vaccination.RecordId];

//70+
/*
Concatenate(QVD_Vaccination)
LOAD
    'VIRTUAL' AS Vaccination.RecordId,
    Vaccination.DateUsedForStatisticsISO,
    Vaccination.ReportingCountry,
    //sum(Vaccination.NumberDosesReceived) AS Vaccination.NumberDosesReceived,  // only reported on target group ALL
    sum(Vaccination.DoseFirst)	AS Vaccination.DoseFirst,
    sum(Vaccination.DoseFirstRefused) AS Vaccination.DoseFirstRefused,
    sum(Vaccination.DoseUnk) AS Vaccination.DoseUnk,
    Vaccination.Region,
    'Age70+' AS Vaccination.TargetGroup,
    Vaccination.Vaccine,
    Vaccination.Population,
    Vaccination.CountryCode,
    Vaccination.LocationCode,
    Vaccination.Reload_Date,
    Vaccination.CountryName,
    //avg(Vaccination.Population) AS Vaccination.Denominator,	// Denominator for ALLP is total population
    sum([Vaccination.Denominator] ) AS [Vaccination.Denominator],
    sum(Vaccination.DoseSecond) AS Vaccination.DoseSecond,
    sum(Vaccination.DoseAdditional1) AS Vaccination.DoseAdditional1
group by  
    Vaccination.DateUsedForStatisticsISO,
    Vaccination.ReportingCountry,
  //  Vaccination.NumberDosesReceived,
    Vaccination.Region,
    Vaccination.Vaccine,
    Vaccination.Population,
    Vaccination.CountryCode,
    Vaccination.LocationCode,
    Vaccination.Reload_Date,
    Vaccination.CountryName;
LOAD *
FROM  $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region]
AND match(Vaccination.TargetGroup, 'Age70_79', 'Age80+') > 0
;
*/



//60+
Concatenate(QVD_Vaccination)
LOAD
    'VIRTUAL' AS Vaccination.RecordId,
    Vaccination.DateUsedForStatisticsISO,
    Vaccination.ReportingCountry,
    //sum(Vaccination.NumberDosesReceived) AS Vaccination.NumberDosesReceived,  // only reported on target group ALL
    sum(Vaccination.DoseFirst)	AS Vaccination.DoseFirst,
    sum(Vaccination.DoseFirstRefused) AS Vaccination.DoseFirstRefused,
    sum(Vaccination.DoseUnk) AS Vaccination.DoseUnk,
    Vaccination.Region,
    'Age60+' AS Vaccination.TargetGroup,
    Vaccination.Vaccine,
    Vaccination.Population,
    Vaccination.CountryCode,
    Vaccination.LocationCode,
    Vaccination.Reload_Date,
    Vaccination.CountryName,
    //avg(Vaccination.Population) AS Vaccination.Denominator,	// Denominator for ALLP is total population
    sum([Vaccination.Denominator] ) AS [Vaccination.Denominator],
    sum(Vaccination.DoseSecond) AS Vaccination.DoseSecond,
    sum(Vaccination.DoseAdditional1) AS Vaccination.DoseAdditional1
group by  
    Vaccination.DateUsedForStatisticsISO,
    Vaccination.ReportingCountry,
  //  Vaccination.NumberDosesReceived,
    Vaccination.Region,
    Vaccination.Vaccine,
    Vaccination.Population,
    Vaccination.CountryCode,
    Vaccination.LocationCode,
    Vaccination.Reload_Date,
    Vaccination.CountryName;
LOAD *
FROM  $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region]
AND (match(Vaccination.TargetGroup, 'Age60_69', 'Age70_79', 'Age80+') > 0 OR (match(Vaccination.TargetGroup, '1_Age60+') and [Vaccination.CountryCode] = 'DE')) // DE reported 60+ but not disaggregated groups 60-70-80+
;

//50+
/*
Concatenate(QVD_Vaccination)
LOAD
    'VIRTUAL' AS Vaccination.RecordId,
    Vaccination.DateUsedForStatisticsISO,
    Vaccination.ReportingCountry,
    //sum(Vaccination.NumberDosesReceived) AS Vaccination.NumberDosesReceived,  // only reported on target group ALL
    sum(Vaccination.DoseFirst)	AS Vaccination.DoseFirst,
    sum(Vaccination.DoseFirstRefused) AS Vaccination.DoseFirstRefused,
    sum(Vaccination.DoseUnk) AS Vaccination.DoseUnk,
    Vaccination.Region,
    'Age50+' AS Vaccination.TargetGroup,
    Vaccination.Vaccine,
    Vaccination.Population,
    Vaccination.CountryCode,
    Vaccination.LocationCode,
    Vaccination.Reload_Date,
    Vaccination.CountryName,
    //avg(Vaccination.Population) AS Vaccination.Denominator,	// Denominator for ALLP is total population
    sum([Vaccination.Denominator] ) AS [Vaccination.Denominator],
    sum(Vaccination.DoseSecond) AS Vaccination.DoseSecond,
    sum(Vaccination.DoseAdditional1) AS Vaccination.DoseAdditional1
group by  
    Vaccination.DateUsedForStatisticsISO,
    Vaccination.ReportingCountry,
  //  Vaccination.NumberDosesReceived,
    Vaccination.Region,
    Vaccination.Vaccine,
    Vaccination.Population,
    Vaccination.CountryCode,
    Vaccination.LocationCode,
    Vaccination.Reload_Date,
    Vaccination.CountryName;
LOAD *
FROM  $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region]
AND match(Vaccination.TargetGroup, 'Age50_59', 'Age60_69', 'Age70_79', 'Age80+') > 0
;
*/