///$tab 012_LOAD_QVDs
/*
Calendar_Vaccination:
LOAD *, num(PurgeChar([Vaccination.YearWeek], '-W')) AS Vaccination.YearWeekNUM
FROM [lib://QData/2_Projects/22_CoronaVirus/03_Qvd/032_Source/Calendar_Vaccination.qvd]
(qvd);
*/
Tag Vaccination.YearWeek With '$date';


//LOAD *
//FROM $(vG_Connection)$(vG_22_032QVDSource)\Calendar_Vaccination.qvd (qvd);  

Map_EU27_EEA:
Mapping 
LOAD * INLINE [
    F1, F2
    Iceland, EU/EEA
    Liechtenstein, EU/EEA
    Norway, EU/EEA
];

Map_Age_Group:
Mapping 
LOAD * INLINE [
	F1, F2
    Age<18, <18 years
	Age0_4, 0-4 years
	Age5_9, 5-9 years
	Age10_14, 10-14 years
	Age15_17, 15-17 years
    Age18_24, 18-24 years
    Age25_49, 25-49 years
    Age50_59, 50-59 years
    Age60+,	60+ years
    Age60_69, 60-69 years
    Age70_79, 70-79 years
    Age80+, 80+ years
];

// 2021-10-28 - Remove and replace by Age60+ 
//     Age60_69, 60-69 years
//     Age70_79, 70-79 years
//     Age80+,	60+ years

// Remove HCW + LTCF in V6.0
// PopGroup:
// LOAD * INLINE [
// "Population Group"
// Total population
// Adults 18+
// Adults 60+
// Children below 18
// Healthcare workers
// LTCF residents
// ];

PopGroup:
LOAD * INLINE [
"Population Group"
Total population
Adults 18+
Adults 60+
Children below 18
];


// Map_Population_Group:
// Mapping 
// LOAD * INLINE [
// 	F1, F2
//     ALLP, Total population
//     ALL, Adults 18+
//     Age<18, Children below 18
//     Age60+,	Adults 60+
//     LTCF, LTCF residents
//    	HCW, Healthcare workers
// ];

Map_Population_Group:
Mapping 
LOAD * INLINE [
	F1, F2
    ALLP, Total population
    ALL, Adults 18+
    Age<18, Children below 18
    Age60+,	Adults 60+
];


Map_Vaccine_ShortName:
Mapping 
LOAD * INLINE [
	Code, Label
	AZ, Vaxzevria
	BECNBG, Beijing CNBG
	COM, Comirnaty 
    JANSS, Janssen
	MOD, Spikevax
    NVXD, Nuvaxovid
	SIN, Sinovac
	SPU, Sputnik V
	UNK, Unknown
    BHACOV, Covaxin
    VLA, Valneva
    COMBA.1, Comirnaty bivalent
    COMBA.4-5, Comirnaty bivalent
    COMBIV, Comirnaty bivalent
    MODBA.1, Spikevax bivalent
    MODBA.4-5, Spikevax bivalent
    MODBIV, Spikevax bivalent
];

Map_Vaccine_FullName:
Mapping 
LOAD * INLINE [
	Code, Label
	AZ, AZD1222 – Vaxzevria
	BECNBG, Inactivated – Beijing CNBG
	COM, Comirnaty – Pfizer/BioNTech
    JANSS, Janssen    
	MOD, Spikevax – Moderna
    NVXD, Nuvaxovid - Novavax
	SIN, Coronavac – Sinovac
	SPU, Sputnik V - Gamaleya Research Institute
	UNK, Unknown
    BHACOV, Covaxin
    VLA, Valneva
    COMBA.1, Comirnaty bivalent
    COMBA.4-5, Comirnaty bivalent
    COMBIV, Comirnaty bivalent
    MODBA.1, Spikevax bivalent
    MODBA.4-5, Spikevax bivalent
    MODBIV, Spikevax bivalent
];


// 20210416 - one or two doses depending on vaccine product
Map_Vaccine_Doses:
Mapping 
LOAD * INLINE [
	Code, Label
	AZ,2
	BECNBG,2
	COM,2
    JANSS,1    
	MOD,2
    NVXD,2
	SIN,2
	SPU,2
	UNK,2
    BHACOV, 2
    VLA, 2
    COMBA.1, 2
    COMBA.4-5, 2
    COMBIV, 2
    MODBA.1, 2
    MODBA.4-5, 2
    MODBIV, 2
];




Last_ReportedWeek:
LOAD
   Vaccination.ReportingCountry, 
   FirstSortedValue(distinct Vaccination.DateUsedForStatisticsISO, -num(MakeWeekDate(left(Vaccination.DateUsedForStatisticsISO, 4), right([Vaccination.DateUsedForStatisticsISO], 2)))) AS Vaccination.LastReportedWeek
Resident QVD_Vaccination
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region]
group by 
 Vaccination.ReportingCountry 
;
   
  
  
  


Last_Denominator:
LOAD
   Vaccination.ReportingCountry, 
   Vaccination.TargetGroup, 
   FirstSortedValue(distinct Vaccination.Denominator, -num(MakeWeekDate(left(Vaccination.DateUsedForStatisticsISO, 4), right([Vaccination.DateUsedForStatisticsISO], 2))), 2) AS Vaccination.LastDenominator
//FROM $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
Resident QVD_Vaccination
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region] 
AND [Vaccination.Denominator] <> '<Missing>' 
    and [Vaccination.Denominator] > 0 
    and len(trim([Vaccination.Denominator]))>0 
    and WildMatch([Vaccination.TargetGroup], '1_*', 'Age60+') = 0
  //  and WildMatch([Vaccination.TargetGroup], '1_*', 'Age60_69', 'Age70_79', 'Age80+', 'Age60+') = 0			// excluded because of 60+ aggregation 
  //  and match(Vaccination.ReportingCountry, 'SE', 'NO') = 0
  //  and WildMatch(Vaccination.ReportingCountry &'|'& [Vaccination.TargetGroup], 'CY|Age*') = 0
  //  and WildMatch(Vaccination.ReportingCountry &'|'& [Vaccination.TargetGroup], 'SK|Age*') = 0
  //  and WildMatch(Vaccination.ReportingCountry &'|'& [Vaccination.TargetGroup], 'IE|2021-W2*') = 0
  //  and WildMatch(Vaccination.ReportingCountry &'|'& [Vaccination.TargetGroup], 'SE|HCW*') = 0
  // and WildMatch(Vaccination.ReportingCountry &'|'& [Vaccination.TargetGroup], 'BE|ALL') = 0
group by 	
	Vaccination.ReportingCountry, 
    Vaccination.TargetGroup;
 
// ensure for 60+ that we have the correct total denominator because sometimes discontinuity in underlying age groups/vaccines then step 009 might have underestimated denominators for 60+

temp_FindDeno_60:
LOAD distinct 
   Vaccination.ReportingCountry, 
   Vaccination.TargetGroup, 
   [Vaccination.Denominator] AS Vaccination.LastDenominator_tmp
//FROM $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
Resident QVD_Vaccination
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region] 
AND [Vaccination.Denominator] <> '<Missing>' 
    and [Vaccination.Denominator] > 0 
    and len(trim([Vaccination.Denominator]))>0 
    and WildMatch([Vaccination.TargetGroup], 'Age60+')>0//, 'Age70_79', 'Age80+') > 0
   // and (Vaccination.ReportingCountry &'|'& Vaccination.DateUsedForStatisticsISO = 'SE|2021-W37'
   //      or Vaccination.ReportingCountry &'|'& Vaccination.DateUsedForStatisticsISO = 'NO|2021-W44')
    ;

Concatenate(Last_Denominator) 
LOAD 
	Vaccination.ReportingCountry, 
    'Age60+' AS Vaccination.TargetGroup,
    max(Vaccination.LastDenominator_tmp) AS [Vaccination.LastDenominator]
resident temp_FindDeno_60
GROUP by Vaccination.ReportingCountry;
drop Table temp_FindDeno_60;


// Cartesian Product to generate all the reported week for country that have not reported for the last available week 
// then we can accumulate until max week
temp_vaccination:
LOAD distinct
	Vaccination.ReportingCountry,
    Vaccination.CountryName,
    Vaccination.TargetGroup,
    Vaccination.Vaccine 
  //  Vaccination.Denominator
   //if(Vaccination.ReportingCountry = 'DK' and Vaccination.TargetGroup = 'LTCF', 43467, [Vaccination.Denominator]) AS  [Vaccination.Denominator] // 20210409 - DK LTCF KO denominator
//FROM $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
Resident QVD_Vaccination
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region] 
and WildMatch([Vaccination.TargetGroup], '1_*') = 0 
//and WildMatch([Vaccination.TargetGroup], '1_*', 'Age60_69', 'Age70_79', 'Age80+') = 0   // filter age 60+/60- because recompute afterwards section (010)
;// and (Vaccination.ReportingCountry&'|'&[Vaccination.TargetGroup] <> 'CY|Age80+') ; //and [Vaccination.Denominator] <> '<Missing>';


 
LEFT JOIN (temp_vaccination)
LOAD 
	Vaccination.ReportingCountry, 
    Vaccination.TargetGroup,
    Vaccination.LastDenominator AS [Vaccination.Denominator]
Resident Last_Denominator;

Drop table Last_Denominator;

JOIN (temp_vaccination)
LOAD distinct Vaccination.DateUsedForStatisticsISO
Resident QVD_Vaccination
//FROM $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region];

JOIN (temp_vaccination)
LOAD distinct [Vaccination.ReportingCountry], [Vaccination.Vaccine]
Resident QVD_Vaccination
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region];
//FROM $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)

LEFT JOIN (temp_vaccination)
LOAD 
	Vaccination.ReportingCountry, 
    Vaccination.LastReportedWeek,
    AutoNumber(Vaccination.LastReportedWeek) AS Vaccination.LastReportedWeekID
Resident Last_ReportedWeek;
Drop table Last_ReportedWeek;


LEFT JOIN (temp_vaccination)
LOAD
    Vaccination.RecordId,
    Vaccination.DateUsedForStatisticsISO, 
    Vaccination.ReportingCountry,
    Vaccination.NumberDosesReceived,
    Vaccination.NumberDosesExported,
    Vaccination.DoseFirst,
    Vaccination.DoseFirstRefused,
    Vaccination.DoseSecond,
    Vaccination.DoseAdditional1,
    Vaccination.DoseAdditional2,
    Vaccination.DoseUnk,
    Vaccination.Region,
    Vaccination.TargetGroup,
    Vaccination.Vaccine,
    Vaccination.Population,
    Vaccination.CountryCode,
    Vaccination.LocationCode,
    Vaccination.Reload_Date,
    Vaccination.CountryName
  //  [Vaccination.Denominator]
  //  if(Vaccination.ReportingCountry = 'DK' and Vaccination.TargetGroup = 'LTCF', 43467, [Vaccination.Denominator]) AS  [Vaccination.Denominator] // 20210409 - DK LTCF KO denominator
Resident QVD_Vaccination
//FROM $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region]
and WildMatch([Vaccination.TargetGroup], '1_*') = 0   // filter age 60+/60- because recompute afterwards section (010)
	//and WildMatch(Vaccination.ReportingCountry &'|'& [Vaccination.TargetGroup], 'CY|Age*') = 0
    //and WildMatch(Vaccination.ReportingCountry &'|'& [Vaccination.TargetGroup], 'SK|Age*') = 0
    //and WildMatch(Vaccination.ReportingCountry &'|'& [Vaccination.TargetGroup], 'BE|ALL') = 0
;// and WildMatch(Vaccination.ReportingCountry &'|'& [Vaccination.TargetGroup], 'SE|HCW*') = 0;

Vaccination:
LOAD 
	*,
    if ( IsNull([Age Group]) = 0, [Member State] & ' - ' & [Age Group]	) 			as [Member State - Age Group],
    
    // Dose administered and Uptake for ALL (population > 17 years old)
	if ( Vaccination.TargetGroup = 'ALL', Vaccination.DoseTotal)					as DoseTotal_ALL,
    if ( Vaccination.TargetGroup = 'ALL',  IF(Vaccination.VaccineTreatmentDoses = 1, 0, 	Vaccination.DoseFirst))					as Dose1st_ALL,
 //   if ( Vaccination.TargetGroup = 'ALL',  Vaccination.DoseFirst)					as Dose1st_ALL, 
    if ( Vaccination.TargetGroup = 'ALL', 	Vaccination.DoseSecond)	as Dose2nd_ALL,
    if ( Vaccination.TargetGroup = 'ALL', [Vaccination.DoseAdd])				    as DoseAdd_ALL,
    if ( Vaccination.TargetGroup = 'ALL', [Vaccination.DoseAdd2])				    as DoseAdd2_ALL,
    if ( Vaccination.TargetGroup = 'ALL', [Vaccination.DoseUnk])					as DoseUnk_ALL,
    
    if ( Vaccination.TargetGroup = 'ALL', Vaccination.Uptake1st)					as Uptake1st_ALL,
    if ( Vaccination.TargetGroup = 'ALL', Vaccination.Uptake2nd)					as Uptake2nd_ALL,
    if ( Vaccination.TargetGroup = 'ALL', Vaccination.UptakeAdd)					as UptakeAdd_ALL,
    if ( Vaccination.TargetGroup = 'ALL', Vaccination.UptakeAdd2)					as UptakeAdd2_ALL,
     
    if ( Vaccination.TargetGroup = 'ALL', Vaccination.UptakeTotal)					as UptakeTotal_ALL,
    
    // Dose administered and Uptake for ALL (population > 17 years old)
	if ( Vaccination.TargetGroup = 'ALLP', Vaccination.DoseTotal)					as DoseTotal_ALLP,
    if ( Vaccination.TargetGroup = 'ALLP',  IF(Vaccination.VaccineTreatmentDoses = 1, 0, 	Vaccination.DoseFirst))					as Dose1st_ALLP,
 //  if ( Vaccination.TargetGroup = 'ALLP',  Vaccination.DoseFirst)					as Dose1st_ALLP,
    if ( Vaccination.TargetGroup = 'ALLP', Vaccination.DoseSecond)					as Dose2nd_ALLP,
    if ( Vaccination.TargetGroup = 'ALLP', [Vaccination.DoseUnk])					as DoseUnk_ALLP,
    if ( Vaccination.TargetGroup = 'ALLP', [Vaccination.DoseAdd])				    as DoseAdd_ALLP,
    if ( Vaccination.TargetGroup = 'ALLP', [Vaccination.DoseAdd2])				    as DoseAdd2_ALLP,
    
    if ( Vaccination.TargetGroup = 'ALLP', Vaccination.Uptake1st)					as Uptake1st_ALLP,
    if ( Vaccination.TargetGroup = 'ALLP', Vaccination.Uptake2nd)					as Uptake2nd_ALLP,
    if ( Vaccination.TargetGroup = 'ALLP', Vaccination.UptakeAdd)					as UptakeAdd_ALLP,
     if ( Vaccination.TargetGroup = 'ALLP', Vaccination.UptakeAdd2)					as UptakeAdd2_ALLP,
    if ( Vaccination.TargetGroup = 'ALLP', Vaccination.UptakeTotal)					as UptakeTotal_ALLP,
    

    // Dose administered and Uptake for people age 60+
    if ( Vaccination.TargetGroup = 'Age60+', IF(Vaccination.VaccineTreatmentDoses = 1, 0, 	Vaccination.DoseFirst))					as Dose1st_60,
   // if ( Vaccination.TargetGroup = 'Age60+', Vaccination.DoseFirst)					as Dose1st_60,
    if ( Vaccination.TargetGroup = 'Age60+', IF(Vaccination.VaccineTreatmentDoses = 1, Vaccination.DoseFirst, 	Vaccination.DoseSecond))	as Dose2nd_60,   
    if ( Vaccination.TargetGroup = 'Age60+', [Vaccination.DoseAdd])				    as DoseAdd_60,
    if ( Vaccination.TargetGroup = 'Age60+', [Vaccination.DoseAdd2])				as DoseAdd2_60,
    if ( Vaccination.TargetGroup = 'Age60+', [Vaccination.DoseUnk])					as DoseUnk_60,
    
    if ( Vaccination.TargetGroup = 'Age60+', Vaccination.Uptake1st)					as Uptake1st_60,
    if ( Vaccination.TargetGroup = 'Age60+', Vaccination.Uptake2nd)					as Uptake2nd_60,
    if ( Vaccination.TargetGroup = 'Age60+', Vaccination.UptakeAdd)					as UptakeAdd_60,
    if ( Vaccination.TargetGroup = 'Age60+', Vaccination.UptakeAdd2)				as UptakeAdd2_60,
    if ( Vaccination.TargetGroup = 'Age60+', Vaccination.UptakeTotal)				as UptakeTotal_60, 
    
    
    // Doses adminsitered and Uptake for Target Group = Health Care Workers
    if ( Vaccination.TargetGroup = 'HCW', Vaccination.Uptake1st)					as Uptake1st_HCW,
    if ( Vaccination.TargetGroup = 'HCW', Vaccination.Uptake2nd)					as Uptake2nd_HCW,
    if ( Vaccination.TargetGroup = 'HCW', Vaccination.UptakeAdd)					as UptakeAdd_HCW,
    if ( Vaccination.TargetGroup = 'HCW',  IF(Vaccination.VaccineTreatmentDoses = 1, 0, 	Vaccination.DoseFirst))					as Dose1st_HCW,
    if ( Vaccination.TargetGroup = 'HCW',  Vaccination.DoseSecond)		as Dose2nd_HCW,
    if ( Vaccination.TargetGroup = 'HCW', [Vaccination.DoseAdd])				    as DoseAdd_HCW,
    if ( Vaccination.TargetGroup = 'HCW', [Vaccination.DoseAdd2])				    as DoseAdd2_HCW,
    if ( Vaccination.TargetGroup = 'HCW', [Vaccination.DoseUnk])					as DoseUnk_HCW,
    if ( Vaccination.TargetGroup = 'HCW', Vaccination.DoseTotal)					as DoseTotal_HCW,
    if ( Vaccination.TargetGroup = 'HCW', Vaccination.UptakeTotal)					as UptakeTotal_HCW, 
    
    // Doses adminsitered and Uptake for Target Group = Health Care Workers
    if ( Vaccination.TargetGroup = 'LTCF', Vaccination.Uptake1st)					as Uptake1st_LTCF,
    if ( Vaccination.TargetGroup = 'LTCF', Vaccination.Uptake2nd)					as Uptake2nd_LTCF,
    if ( Vaccination.TargetGroup = 'LTCF', Vaccination.UptakeAdd)					as UptakeAdd_LTCF,
    if ( Vaccination.TargetGroup = 'LTCF', IF(Vaccination.VaccineTreatmentDoses = 1, 0, 	Vaccination.DoseFirst))				as Dose1st_LTCF,
    if ( Vaccination.TargetGroup = 'LTCF', Vaccination.DoseSecond)	as Dose2nd_LTCF,
    if ( Vaccination.TargetGroup = 'LTCF', [Vaccination.DoseAdd])				    as DoseAdd_LTCF,
    if ( Vaccination.TargetGroup = 'LTCF', [Vaccination.DoseAdd2])				    as DoseAdd2_LTCF,
    if ( Vaccination.TargetGroup = 'LTCF', [Vaccination.DoseUnk])					as DoseUnk_LTCF,
    if ( Vaccination.TargetGroup = 'LTCF', Vaccination.DoseTotal)					as DoseTotal_LTCF,
    if ( Vaccination.TargetGroup = 'LTCF', Vaccination.UptakeTotal)					as UptakeTotal_LTCF, 
    
    
    // Doses adminsitered and Uptake for Target Group Age
    if ( IsNull([Age Group]) = 0,  IF(Vaccination.VaccineTreatmentDoses = 1, 0, 	Vaccination.DoseFirst))					as Dose1st_AGE,
    if ( IsNull([Age Group]) = 0, [Vaccination.DoseSecond])							as Dose2nd_AGE,
    if (IsNull([Age Group]) = 0, [Vaccination.DoseAdd])							    as DoseAdd_AGE,
    if (IsNull([Age Group]) = 0, [Vaccination.DoseAdd2])							as DoseAdd2_AGE,
    if ( IsNull([Age Group]) = 0, Vaccination.DoseUnk)								as DoseUnk_AGE,
    if ( IsNull([Age Group]) = 0, Vaccination.DoseTotal)							as DoseTotal_AGE,
    
    if ( IsNull([Age Group]) = 0, Vaccination.Uptake1st)							as Uptake1st_AGE,
    if ( IsNull([Age Group]) = 0, Vaccination.Uptake2nd)							as Uptake2nd_AGE,
    if ( IsNull([Age Group]) = 0, Vaccination.UptakeAdd)							as UptakeAdd_AGE,
    if ( IsNull([Age Group]) = 0, Vaccination.UptakeAdd2)							as UptakeAdd2_AGE,
    if ( IsNull([Age Group]) = 0, Vaccination.UptakeTotal)							as UptakeTotal_AGE, 
    
    // Doses Distributed to Countries (absolute and per 100 Inhabitants)
    if ( Vaccination.TargetGroup = 'ALL' AND Vaccination.NumberDosesReceived > 0,  
    	 Vaccination.NumberDosesReceived, '<Missing>') 								as DosesDistributed,
         
    if ( Vaccination.TargetGroup = 'ALLP' AND Vaccination.NumberDosesReceived > 0,   
  	  Vaccination.NumberDosesReceived, '<Missing>') / [Vaccination.Population] 		as DosesDistributed_per100Inh,
      
    if ( Vaccination.TargetGroup = 'ALLP' AND Vaccination.DoseTotal > 0,   
  	  Vaccination.DoseTotal, '<Missing>') / Vaccination.Denominator 				as DosesAdministered_per100Inh,
      
    // Doses Exported
    // Doses Distributed to Countries (absolute and per 100 Inhabitants)
    if ( Vaccination.TargetGroup = 'ALL' AND Vaccination.NumberDosesExported > 0,   
    	 Vaccination.NumberDosesExported, '<Missing>')								as DoseExported,
   
   if(match(Vaccination.TargetGroup, 'Age0_4', 'Age5_9', 'Age10_14', 'Age15_17', 'Age60_69', 'Age70_79', 'Age80+', 'AgeUNK' ) > 0, null(), [Age Group]) 	AS [_DimAgeGroupFiltered],
   if(match(Vaccination.TargetGroup, 'Age0_4', 'Age5_9','Age<18', 'Age60_69', 'Age70_79', 'Age80+', 'AgeUNK' ) > 0, null(), [Age Group]) 					AS [_DimAgeGroupFiltered_N],
   if(match(Vaccination.TargetGroup, 'Age0_4', 'Age5_9', 'Age<18', 'Age60+', 'AgeUNK' ) > 0, null(), [Age Group]) 					AS [_DimAgeGroupFilteredBooster],
   if(match(Vaccination.TargetGroup, 'Age0_4', 'Age5_9', 'Age10_14', 'Age15_17', 'Age60+', 'AgeUNK' ) > 0, null(), [Age Group]) 					AS [_DimAgeGroupFilteredBooster2]

;
LOAD 
	*,
    Vaccination.ReportingCountry &'|'&Vaccination.TargetGroup&'|'&Vaccine&'|'&Vaccination.YearWeek  AS %Key_Cumul_KPI,
    
    ApplyMap('Map_Age_Group', [Vaccination.TargetGroup], null() )								as [Age Group],
    ApplyMap('Map_Population_Group', [Vaccination.TargetGroup], null())							as [Population Group],
    
// 20210416
//	rangesum( Vaccination.DoseFirst, Vaccination.DoseSecond, Vaccination.DoseUnk)	as Vaccination.DoseTotal,

	//20220202 - v5.2.2 - take into account also second doses of JANSSEN
  //  rangesum( Vaccination.DoseFirst, Vaccination.DoseSecond, Vaccination.DoseUnk, Vaccination.DoseAdd) as Vaccination.DoseTotal,
  
  IF(Vaccination.VaccineTreatmentDoses = 1 
    ,rangesum(Vaccination.DoseSecond,  Vaccination.DoseUnk, Vaccination.DoseAdd, [Vaccination.DoseAdd2])
    ,rangesum( Vaccination.DoseFirst, Vaccination.DoseSecond, Vaccination.DoseUnk, Vaccination.DoseAdd, [Vaccination.DoseAdd2]) ) as Vaccination.DoseTotal, // count(only once for single dose vaccine
  
    // Uptake = #Doses divided by denominator given by Target Group
    rangesum( Vaccination.DoseFirst) / Vaccination.Denominator 														as Vaccination.Uptake1st,
    // 20220202 - v5.2.2 - Uptake full - Jannssen Single dose count full vax + use of 2nd doses of Janssen to complete first doses
    rangesum(  Vaccination.DoseSecond ) / Vaccination.Denominator	  
    																												as Vaccination.Uptake2nd,    
   // rangesum( IF(Vaccination.VaccineTreatmentDoses = 1, Vaccination.DoseFirst, 	Vaccination.DoseSecond) ) / Vaccination.Denominator	
   // 																												as Vaccination.Uptake2nd,    // must count single dose vaccine as full vaccinated
    rangesum( Vaccination.DoseAdd) / Vaccination.Denominator 														as Vaccination.UptakeAdd,     
    
    rangesum( Vaccination.DoseAdd2) / Vaccination.Denominator 														as Vaccination.UptakeAdd2,
    
    IF(Vaccination.VaccineTreatmentDoses = 1 
    ,rangesum(Vaccination.DoseSecond,  Vaccination.DoseUnk, Vaccination.DoseAdd, [Vaccination.DoseAdd2])
    ,rangesum( Vaccination.DoseFirst, Vaccination.DoseSecond, Vaccination.DoseUnk, Vaccination.DoseAdd, [Vaccination.DoseAdd2]) ) / Vaccination.Denominator 		as Vaccination.UptakeTotal,

;   
LOAD  
	Vaccination.RecordId,
    Vaccination.DateUsedForStatisticsISO AS Vaccination.YearWeek,
    num(PurgeChar(Vaccination.DateUsedForStatisticsISO , '-W')) AS Vaccination.YearWeekNUM,
    Vaccination.LastReportedWeek,
    if(Vaccination.DateUsedForStatisticsISO > Vaccination.LastReportedWeek, null(), 1) AS _Flag_WeekToReport, 
    if(Vaccination.DateUsedForStatisticsISO <= Vaccination.LastReportedWeek, Vaccination.DateUsedForStatisticsISO, null()) AS Vaccination.YearWeekReported,
    Vaccination.ReportingCountry,
    Vaccination.Denominator,
  //   if(Vaccination.ReportingCountry = 'NL', 0, Vaccination.Denominator) AS [Vaccination.Denominator], // 20210409 - Netherlands to reported Doses UNK only , set 0 to remove from denominator total EU uptake.
  //   Vaccination.Denominator 											 AS Vaccination.Denominator_Original, // because we need to compute doses per inhabitants for NL altough unknow reported
    Vaccination.NumberDosesReceived,
    [Vaccination.NumberDosesExported],
    [Vaccination.DoseFirstRefused],
    Vaccination.DoseFirst,
    Vaccination.DoseSecond,
    Vaccination.DoseAdditional1 AS Vaccination.DoseAdd,
    Vaccination.DoseAdditional2 AS Vaccination.DoseAdd2,
    Vaccination.DoseUnk,
    Vaccination.Region,
    Vaccination.TargetGroup,
//    if(match(Vaccination.TargetGroup, 'Age0_4', 'Age5_9', 'Age10_14', 'Age15_17', 'Age60_69', 'Age70_79', 'Age80+', 'AgeUNK' ) = 0, null(), Vaccination.TargetGroup) AS [_DimAgeGroupFiltered],
 //   if(match(Vaccination.TargetGroup, 'Age0_4', 'Age5_9', 'Age10_14', 'Age15_17', 'Age60+' ) > 0, null(), Vaccination.TargetGroup) AS [_DimAgeGroupFilteredBooster],
    Vaccination.Vaccine													as [Vaccine Code],
    ApplyMap('Map_Vaccine_ShortName', Vaccination.Vaccine, 'Unknown')	as Vaccine,
    ApplyMap('Map_Vaccine_FullName', Vaccination.Vaccine, 'Unknown')	as VaccineFullName,

// 20210416    
    ApplyMap('Map_Vaccine_Doses', Vaccination.Vaccine, 2)	as Vaccination.VaccineTreatmentDoses,    
    
    Vaccination.Population,
    if( Vaccination.CountryCode = 'EL', 'GR', Vaccination.CountryCode) AS Vaccination.CountryCode,
    Vaccination.LocationCode,
    Vaccination.CountryName 		as [Member State]
Resident temp_vaccination;
//FROM $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
//WHERE [Vaccination.ReportingCountry] = [Vaccination.Region];
drop table temp_vaccination;




// Concatenate(Vaccination)
// LOAD 'Bulgaria' as [Member State], 'BG' AS [Vaccination.CountryCode] AutoGenerate 1;
// Concatenate(Vaccination)
// LOAD 'Liechtenstein' as [Member State], 'LI' AS [Vaccination.CountryCode] AutoGenerate 1;