///$tab 016_Data_Completeness
DataCompleteness:
LOAD
   Vaccination.CountryName AS Completeness.Country, 
   if(Vaccination.TargetGroup='ALL', 'ALL_18+', Vaccination.TargetGroup)  AS Completeness.TargetGroup, 
   Vaccination.DateUsedForStatisticsISO AS Completeness.YearWeek
FROM $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region];

/*
JOIN (DataCompleteness)
LOAD DISTINCT Vaccination.TargetGroup AS Completeness.TargetGroup 
FROM $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
WHERE [Vaccination.ReportingCountry] = [Vaccination.Region];
*/