///$tab 017_Subnational
Qualify *; Unqualify Subnational_RegionCode, Vaccination.YearWeek;

Region:
LOAD *,  [Vaccination.Region] AS Subnational_RegionCode
FROM $(vG_Connection)$(vG_22_032QVDSource)\Vaccination_2.qvd (qvd)
WHERE [Vaccination.ReportingCountry] <> [Vaccination.Region]
;

unqualify *;

SubnationalRegions_Shapes: 	
LOAD * FROM $(vG_Connection)$(vG_22_032QVDSource)\SubnationalRegions_Shapes.qvd (qvd) where exists(Subnational_LocationParentCode);