///$tab 020_XLS_INFOS
URLs:
LOAD
    "Member State",
    trim(URL_Plan) AS URL_Plan,
    trim(URL_Rollout) AS URL_Rollout
FROM [lib://QData/2_Projects/22_CoronaVirus/02_ExternalSources/National_Vaccine_URL.xlsx]
(ooxml, embedded labels, table is URL);


Product:
Load Distinct Vaccine, Vaccine as Product_ 
Resident Vaccination WHERE  Vaccination.TargetGroup = 'ALL'
order by Vaccine;
LOAD Distinct Vaccine, 'ALL' as Product_ 
Resident Vaccination WHERE  Vaccination.TargetGroup = 'ALL';

MemberState_Group:
Load Distinct "Member State", "Member State" as MemberState_ 
Resident Vaccination WHERE  Vaccination.TargetGroup = 'ALL'
order by "Member State";
LOAD Distinct "Member State", 'Median EU/EEA' as  MemberState_  
Resident Vaccination WHERE  Vaccination.TargetGroup = 'ALL';

EU27_EEA:
Load Distinct "Member State",
applymap('Map_EU27_EEA', [Member State], 'EU') 		AS EU27_EEA
Resident Vaccination;

Concatenate (EU27_EEA)
LOAD "Member State", 'EU/EEA' AS EU27_EEA
Resident EU27_EEA 
where EU27_EEA = 'EU';



NoteOnDataXLS:
LOAD
    "Member State",
    "Notes on data by country"
FROM [lib://QData/2_Projects/22_CoronaVirus/02_ExternalSources/National_Vaccine_URL.xlsx]
(ooxml, embedded labels, table is URL) 
where len(trim("Notes on data by country"))>0;