///$tab 030_Design_Fields
D_BUTTON_ALL_ALLP:
LOAD * INLINE [
	SW_ADULTS_POP, SW_ADULTS_POP_LABEL, SW_ADULTS_POP_LABEL_KPI,  SW_ADULTS_POP_LABEL_N
    ALL, among adults (18+), adults (18+), adults (18+)
    ALLP, in the total population, people, the total population
];

// for the pivot with key figures
KPI:
LOAD * INLINE [KPI_GROUP, KPI_ID, KPI_NAME
Total doses distributed and administered, 10, Total number of vaccine doses distributed by manufactures to countries
Total doses distributed and administered, 20, Number of vaccine doses distributed by manufactures to countries per hundred inhabitants*
Total doses distributed and administered, 30, Total number of vaccine doses administered
Cumulative vaccine uptake, 40, Cumulative uptake of primary course in the total population
Cumulative vaccine uptake, 50, Cumulative uptake of primary course among adults aged 18 years and above
Cumulative vaccine uptake, 60, Cumulative uptake of primary course among adolescents and children below 18 years*
Cumulative vaccine uptake, 70, Cumulative uptake of primary course among persons aged 60 years and above*
Cumulative vaccine uptake, 80, Cumulative uptake of primary course among healthcare workers*
Cumulative vaccine uptake, 90, Cumulative uptake of primary course among residents of long-term care facilities*
Cumulative vaccine uptake, 100, Cumulative uptake of a booster/additional dose in the total population
Cumulative vaccine uptake, 110, Cumulative uptake of a booster/additional dose among adults aged 18 years and above
Cumulative vaccine uptake, 120, Cumulative uptake of a booster/additional dose among persons aged 60 years and above
];

//Total doses distributed and administered, 15, Total number of vaccine doses exported

// for the country summary KPI
TABLE_KPI:
LOAD * INLINE [T_KPI_GROUP, T_KPI_ID, T_KPI_NAME, GROUP_SORT
, 1, Reporting Week, 1
, 2, Total doses administered, 1
Total population, 10, N. with at least one dose, 2
Total population, 20, N. primary courses, 2
Total population, 25, N. booster/additional doses, 2
Total population, 30, Uptake at least one dose (%), 2
Total population, 40, Uptake primary course (%), 2
Total population, 50, Uptake booster/additional dose (%), 2
Adults (18+), 100, N. with at least one dose, 3
Adults (18+), 200, N. primary courses, 3
Adults (18+), 250, N. booster/additional doses, 3
Adults (18+), 300, Uptake at least one dose (%), 3
Adults (18+), 400, Uptake primary course (%),3
Adults (18+), 500, Uptake booster/additional dose (%), 3
];