///$tab VERSION NOTES
/********************* VERSION NOTES  ***********************************************************************
Version 5.0.1 - Uptake additional doses for 60+
Version 5.0 - Beta Realease - Remove 60-69, 70-79, 80+ and replace by 60+
Version 5.0 - Alpha Realease - Additional doses + Doses exported + Target Groups 70+, 60+, 50+
Version 4.2 - Patch 20211013 - Cap Uptake to 100% in Age groups - Table Views
Version 4.2 - Patch 20211007 - Issue with DK Age<18 group
Version 4.2 - Patch 20211005 - Add AgeUNK to doses All Population - Uptake capped 100% Country Profile
Version 4.2 - Summary Key Figures and data completeness
Version 4.1 - include age group <18 years
*/